accounts/urls.py
from django.conf import settings
from django.urls import include, path

from .views import UserRegistrationView, LogoutView, UserLoginView
from . import views

from django.conf.urls.static import static

app_name = 'accounts'

urlpatterns = [
    path(
        "login/", UserLoginView.as_view(),
        name="user_login"
    ),
    path(
        "logout/", LogoutView.as_view(),
        name="user_logout"
    ),
    path(
        "register/", UserRegistrationView.as_view(),
        name="user_registration"
    ),
    # path('captcha/', include('captcha.urls')),
    path('update-email/', views.update_email, name='update_email'),
    path('update-password/', views.update_password, name='update_password'),
    path('delete-account/<int:user_id>/', views.delete_account, name='delete_account'),
]   

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

banking_system/urls.py
from django.contrib import admin
from django.urls import include, path
from django.urls import path, include
# from core.views import HomeView


urlpatterns = [
    # path('', HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path(
        'transactions/',
        include('transactions.urls', namespace='transactions')
    )
]

core/urls.py
from django.conf import settings
from django.urls import path
from . import views

from django.conf.urls.static import static


app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/<int:pk>/like/', views.like_post, name='like_post'),
    path('post/<int:pk>/comment/', views.comment_post, name='comment_post'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('projects/', views.projects, name='projects'),
    path('blogs/', views.blogs, name='blogs'),
    path('team/', views.team, name='team'),
    path('testimonial/', views.testimonial, name='testimonial'),
    path('faq/', views.faq, name='faq'),
    path('contact/', views.contact_view, name='contact'),
    path('error/', views.error, name='error'),
    path('adminpanel/', views.adminpanel, name='adminpanel'),
    path('admin_transactions/', views.admin_transactions, name='admin_transactions'),
    path('admin_users/', views.admin_users, name='admin_users'),
    path('contact-messages/', views.admin_contact, name='admin_contact'),
    path('contact-messages/<int:message_id>/delete/', views.delete_contact, name='delete_contact'),
    path('blog-posts/', views.admin_blog_posts, name='admin_blog_posts'),
    path('blog-posts/add/', views.add_blog_post, name='add_blog_post'),
    path('blog-posts/<int:post_id>/edit/', views.edit_blog_post, name='edit_blog_post'),
    path('blog-posts/<int:post_id>/delete/', views.delete_blog_post, name='delete_blog_post'),
    path('request/', views.fd_rd_request, name='fd_rd_request'),
    path('star-user/', views.star_user, name='star_user'),
    path('notification/', views.user_notifications, name='user_notifications'),
    path('service-request/', views.create_service_request, name='service_request'),
    path('service-request-success/', views.service_request_success, name='service_request_success'),
    path('service-requests/', views.admin_service_requests, name='admin_service_requests'),
    path('service-requests/<int:pk>/<str:status>/', views.change_request_status, name='change_request_status'),
    path('service-requests-status/', views.service_requests_status, name='service_requests_status'),
    path('service-requests/delete/<int:pk>/', views.delete_service_request, name='delete_service_request'),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.exceptions import ValidationError
from django.db import transaction

from .models import User, BankAccountType, UserBankAccount, UserAddress
from .constants import GENDER_CHOICE

class UserAddressForm(forms.ModelForm):

    class Meta:
        model = UserAddress
        fields = [
            'street_address',
            'city',
            'postal_code',
            'country'
        ]

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)

    #     for field in self.fields:
    #         self.fields[field].widget.attrs.update({
    #             'class': (
    #                 'appearance-none block w-full bg-gray-200 '
    #                 'text-gray-700 border border-gray-200 rounded '
    #                 'py-3 px-4 leading-tight focus:outline-none '
    #                 'focus:bg-white focus:border-gray-500'
    #             )
    #         })


class UserRegistrationForm(UserCreationForm):
    account_type = forms.ModelChoiceField(
        queryset=BankAccountType.objects.all()
    )
    gender = forms.ChoiceField(choices=GENDER_CHOICE)
    birth_date = forms.DateField(widget=forms.DateInput(attrs={'placeholder': 'MM/DD/YYYY'}))

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        ]

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)

    #     for field in self.fields:
    #         self.fields[field].widget.attrs.update({
    #             'class': (
    #                 'appearance-none block w-full bg-gray-200 '
    #                 'text-gray-700 border border-gray-200 '
    #                 'rounded py-3 px-4 leading-tight '
    #                 'focus:outline-none focus:bg-white '
    #                 'focus:border-gray-500'
    #             )
    #         })

    @transaction.atomic
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
            account_type = self.cleaned_data.get('account_type')
            gender = self.cleaned_data.get('gender')
            birth_date = self.cleaned_data.get('birth_date')

            UserBankAccount.objects.create(
                user=user,
                gender=gender,
                birth_date=birth_date,
                account_type=account_type,
                account_no=(
                    user.id +
                    settings.ACCOUNT_NUMBER_START_FROM
                )
            )
        return user

from django import forms

class UserLoginForm(forms.Form):
    email = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput())
    captcha = forms.CharField(label='Enter the CAPTCHA')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['captcha'].widget.attrs.update({'autofocus': 'autofocus'})
        
        
##update email

# forms.py
from django import forms

class UpdateEmailForm(forms.Form):
    email = forms.EmailField(label='New Email', max_length=254)


##

class ForgotPasswordForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    # first_name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))
    # last_name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))

        

accounts/views.py
import random
import string
from django.contrib import messages
from django.contrib.auth import get_user_model, login, logout, authenticate
from django.contrib.auth.views import LoginView
from django.http import Http404
from django.shortcuts import HttpResponseRedirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, RedirectView
from flask_login import login_required
from django.contrib.auth.hashers import make_password
from .forms import ForgotPasswordForm, UserRegistrationForm, UserAddressForm, UserLoginForm
from transactions.forms import CustomPasswordChangeForm
from django.contrib.auth import login as auth_login
User = get_user_model()


class UserRegistrationView(TemplateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'accounts/user_registration.html'

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return HttpResponseRedirect(
                reverse_lazy('transactions:profile')
            )
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        registration_form = UserRegistrationForm(self.request.POST)
        address_form = UserAddressForm(self.request.POST)

        if registration_form.is_valid() and address_form.is_valid():
            user = registration_form.save()
            address = address_form.save(commit=False)
            address.user = user
            address.save()
            auth_login(request, user, backend='accounts.models.CustomAuthBackend')
            messages.success(
                self.request,
                (
                    f'Thank You For Creating A Bank Account. '
                    f'Your Account Number is {user.account.account_no}. '
                )
            )
            return HttpResponseRedirect(
                reverse_lazy('transactions:profile')
            )

        return self.render_to_response(
            self.get_context_data(
                registration_form=registration_form,
                address_form=address_form
            )
        )

    def get_context_data(self, **kwargs):
        if 'registration_form' not in kwargs:
            kwargs['registration_form'] = UserRegistrationForm()
        if 'address_form' not in kwargs:
            kwargs['address_form'] = UserAddressForm()

        return super().get_context_data(**kwargs)

###


# from django.shortcuts import render, redirect
# from django.contrib.auth import authenticate, login
from django.views import View
# from .forms import UserLoginForm
# import random

def generate_captcha():
    return str(random.randint(100000, 999999))

def set_captcha_session(request):
    captcha = generate_captcha()
    request.session['captcha'] = captcha

class UserLoginView(View):
    #only unauthenticated user can access login page after authentication
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.user.is_superuser:  # Check if the user is an admin
                return redirect('core:adminpanel')  
            return redirect('transactions:profile')  
        return super().dispatch(request, *args, **kwargs)
        
    def get(self, request):
        form = UserLoginForm()
        set_captcha_session(request)
        return render(request, 'accounts/user_login.html', {'form': form})

    def post(self, request):
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['email']
            password = form.cleaned_data['password']
            entered_captcha = form.cleaned_data['captcha']
            
            # Validate captcha
            if entered_captcha == request.session.get('captcha'):
                # Clear captcha session
                del request.session['captcha']
                
                user = authenticate(username=username, password=password)
                if user is not None:
                    login(request, user)
                    if user.is_superuser:  # Check if the user is an admin
                        return redirect('core:adminpanel')  
                    return redirect('transactions:profile') 
                else:
                    form.add_error(None, 'Invalid username or password.')
            else:
                form.add_error('captcha', 'Incorrect captcha.')
        
        return render(request, 'accounts/user_login.html', {'form': form})
####


class LogoutView(RedirectView):
    pattern_name = 'core:index'

    def get_redirect_url(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            logout(self.request)
        return super().get_redirect_url(*args, **kwargs)

from django.contrib.auth.hashers import check_password

def change_password_view(request):
    if request.method == 'POST':
        form = CustomPasswordChangeForm(request.POST)
        if form.is_valid():
            current_password = form.cleaned_data['current_password']
            new_password1 = form.cleaned_data['new_password1']
            new_password2 = form.cleaned_data['new_password2']
            user = request.user
            if check_password(current_password, user.password):
                # Password is correct, so update the password
                user.set_password(new_password1)
                user.save()
                return HttpResponseRedirect('/success/')
            else:
                # Password is incorrect, so show an error message
                raise Http404("Page not found")
    else:
        form = CustomPasswordChangeForm()
    return render(request, 'transactions/profile.html', {'form': form})



##update email


from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UpdateEmailForm

# @login_required
# def update_email(request):
#     if request.method == 'POST':
#         form = UpdateEmailForm(request.POST)
#         if form.is_valid():
#             new_email = form.cleaned_data['email']
#             request.user.email = new_email
#             request.user.save()
#             messages.success(request, 'Your email has been updated successfully.')
#             return redirect(reverse('accounts:update_email'))
#     else:
#         form = UpdateEmailForm(initial={'email': request.user.email})
#     return render(request, 'accounts/update_email.html', {'form': form})

##vulnerable csrf

from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls import reverse
from .forms import UpdateEmailForm

@login_required
def update_email(request):
    if request.method == 'POST':
        form = UpdateEmailForm(request.POST)
        if form.is_valid():
            new_email = form.cleaned_data['email']
            # Ensure to handle cases where request.user is AnonymousUser
            if not request.user.is_anonymous:
                request.user.email = new_email
                request.user.save()
                messages.success(request, 'Your email has been updated successfully.')
            else:
                messages.error(request, 'You are not logged in.')
            return redirect(reverse('accounts:update_email'))
    else:
        form = UpdateEmailForm(initial={'email': request.user.email if not request.user.is_anonymous else ''})
    return render(request, 'accounts/update_email.html', {'form': form})



##end update email




# update/forgot password
def generate_random_password(length=6):
    characters = string.ascii_letters + string.digits
    return ''.join(random.choice(characters) for _ in range(length))

def update_password(request):
    if request.method == 'POST':
        form = ForgotPasswordForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            # first_name = form.cleaned_data['first_name']
            # last_name = form.cleaned_data['last_name']
            
            try:
                # user = User.objects.get(email=email, first_name=first_name, last_name=last_name)
                user = User.objects.get(email=email)
                new_password = generate_random_password()
                user.password = make_password(new_password)
                user.save()
                
                
                messages.success(request, f'Your new password is: {new_password}')
                
                return redirect('accounts:update_password')
            except User.DoesNotExist:
                messages.error(request, 'User with provided details does not exist.')
    else:
        form = ForgotPasswordForm()

    return render(request, 'accounts/update_password.html', {'form': form})
    







##

# In views.py
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.decorators import user_passes_test
from .models import User

@user_passes_test(lambda u: u.is_superuser)
def delete_account(request, user_id):
    user = get_object_or_404(User, id=user_id)
    if not user.is_superuser:  # Ensure the user being deleted is not an admin
        user.delete()
    return redirect('core:admin_users')

templates/accounts/update_email.html
{% extends 'core/base.html' %}

{% block head_title %}Update Email{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center mb-4">Update Email</h1>
    <hr>

    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post" action="{% url 'accounts:update_email' %}" class="bg-white shadow-sm p-4 rounded">
                 {% csrf_token %} 
                <div id="account-update-email" class="py-4">
                    <h4 class="font-weight-bold mb-4">Update Email</h4>
                    <div class="bg-light p-4 rounded">
                        <div class="mb-4">
                            <label for="email" class="font-weight-bold">New Email :</label>
                            {{ form.email }}
                            {% if form.email.errors %}
                                <p class="text-danger">{{ form.email.errors }}</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <button class="btn btn-primary mt-3" type="submit">Update Email</button>
            </form>
        </div>
    </div>
</div>
<br>
{% endblock %}

templates/accounts/update_password.html
{% extends 'core/base.html' %}

{% block head_title %}Update Password{% endblock %}

{% block content %}
<style>
    .background {
        background: linear-gradient(to bottom right, #5899E2, #5899E2, #FFFFFF, lightblue);
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
        backdrop-filter: blur(10px);
    }
    .form-container {
        background-color: rgba(255, 255, 255, 0.2);
        max-width: 500px;
        padding: 40px;
        width: 400px;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        margin-top: 40px;
        margin-bottom: 40px;
    }
    .form-title {
        font-family: 'Monospace', sans-serif;
        font-weight: bold;
        font-size: 1.875rem;
        text-align: center;
        margin-bottom: 20px;
    }
    .form-card {
        margin-top: 20px;
    }
    .form-label {
        display: block;
        font-weight: bold;
        margin-bottom: 8px;
        color:#273746;
    }
    .form-control {
        width: 100%;
        padding: 10px;
        margin-bottom: 15px;
        border: 1px solid rgba(255, 255, 255, 0.3);
        border-radius: 5px;
        font-size: 1rem;
        background-color: rgba(255, 255, 255, 0.3);
        backdrop-filter: blur(5px);
    }
    .submit-button {
        background-color: #4299e1;
        color: white;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
        font-size: 1rem;
        transition: background-color 0.3s ease;
    }
    .submit-button:hover {
        background-color: #2b6cb0;
    }
</style>

<div class="background">
    <div class="form-container">
        <h2 class="form-title">Forgot Password</h2>
        <form method="post" class="form-card">
            {% csrf_token %}
            <div class="mb-4">
                <label for="{{ form.email.id_for_label }}" class="form-label">Email address</label>
                <input type="text" name="{{ form.email.name }}" id="{{ form.email.id_for_label }}" class="form-control">
            </div>
            {% comment %} <div class="mb-4">
                <label for="{{ form.first_name.id_for_label }}" class="form-label">First Name</label>
                <input type="text" name="{{ form.first_name.name }}" id="{{ form.first_name.id_for_label }}" class="form-control">
            </div>
            <div class="mb-4">
                <label for="{{ form.last_name.id_for_label }}" class="form-label">Last Name</label>
                <input type="text" name="{{ form.last_name.name }}" id="{{ form.last_name.id_for_label }}" class="form-control">
            </div> {% endcomment %}
            <div class="flex items-center justify-center">
                <button type="submit" class="submit-button">Reset Password</button>
            </div>
        </form>
        <div>
            {% if messages %}
                <div class="mt-4">
                    {% for message in messages %}
                        <div class="alert alert-info">{{ message }}</div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/user_login.html
{% extends 'core/base.html' %}
{% block head_title %}User Login{% endblock %}
{% load static %}
{% block content %}
<style>
    .background {
        background: linear-gradient(to bottom right, #5899E2, #5899E2, #FFFFFF, lightblue);
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
        backdrop-filter: blur(10px); /* Adjust blur strength as needed */
    }
    .form-container {
        background-color: rgba(255, 255, 255, 0.2); /* Adjust opacity as needed */
        max-width: 500px;
        padding: 40px;
        width: 400px;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        margin-top: 40px; /* Adjust top margin for space below header */
        margin-bottom: 40px; /* Adjust bottom margin for space above footer */
    }
    .form-title {
        font-family: 'Monospace', sans-serif;
        font-weight: bold;
        font-size: 1.875rem; /* 30px */
        text-align: center;
        margin-bottom: 20px;
    }
    .form-card {
        margin-top: 20px;
    }
    .form-label {
        display: block;
        font-weight: bold;
        margin-bottom: 8px;
        color:#273746;
    }
    .form-control {
        width: 100%; /* Adjust width as needed */
        padding: 10px;
        margin-bottom: 15px;
        border: 1px solid rgba(255, 255, 255, 0.3); /* Transparent border */
        border-radius: 5px;
        font-size: 1rem; /* 16px */
        background-color: rgba(255, 255, 255, 0.3); /* Transparent background */
        backdrop-filter: blur(5px); /* Optional: Apply blur effect to input field */
    }
    .submit-button {
        background-color: #4299e1; /* Blue color */
        color: white;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
        font-size: 1rem; /* 16px */
        transition: background-color 0.3s ease;
    }
    .submit-button:hover {
        background-color: #2b6cb0; /* Darker blue on hover */
    }
</style>

<div class="background">
    <div class="form-container">
        <h1 class="form-title">Sign In</h1>
        <form method="post" class="form-card">
            {% csrf_token %}
            
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                {% endfor %}
            {% endif %}
            
            <div class="mb-4">
                <label for="{{ form.email.id_for_label }}" class="form-label">Email:</label>
                <input type="text" name="{{ form.email.name }}" id="{{ form.email.id_for_label }}" class="form-control">
                {% if form.email.errors %}
                    {% for error in form.email.errors %}
                        <p class="error-message">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>
            
            <div class="mb-4">
                <label for="{{ form.password.id_for_label }}" class="form-label">Password:</label>
                <input type="password" name="{{ form.password.name }}" id="{{ form.password.id_for_label }}" class="form-control">
                {% if form.password.errors %}
                    {% for error in form.password.errors %}
                        <p class="error-message">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>

            <!-- Captcha field -->
            <div class="mb-4">
                <label for="id_captcha" class="form-label">Enter Captcha:</label>
                <input type="text" name="captcha" id="id_captcha" class="form-control" placeholder="Enter Captcha">
                {% if form.captcha.errors %}
                    <p class="error-message">{{ form.captcha.errors }}</p>
                {% endif %}
                <p class="captcha-text">Captcha: <strong>{{ request.session.captcha }}</strong></p>
            </div>

            <div class="flex items-center justify-center">
                <button class="submit-button" type="submit">
                    Sign In
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}