accounts/urls.py
from django.conf import settings
from django.urls import include, path

from .views import UserRegistrationView, LogoutView, UserLoginView
from . import views

from django.conf.urls.static import static

app_name = 'accounts'

urlpatterns = [
    path(
        "login/", UserLoginView.as_view(),
        name="user_login"
    ),
    path(
        "logout/", LogoutView.as_view(),
        name="user_logout"
    ),
    path(
        "register/", UserRegistrationView.as_view(),
        name="user_registration"
    ),
    # path('captcha/', include('captcha.urls')),
    path('update-email/', views.update_email, name='update_email'),
    path('update-password/', views.update_password, name='update_password'),
    path('delete-account/<int:user_id>/', views.delete_account, name='delete_account'),
]   

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

banking_system/urls.py
from django.contrib import admin
from django.urls import include, path
from django.urls import path, include
# from core.views import HomeView


urlpatterns = [
    # path('', HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path(
        'transactions/',
        include('transactions.urls', namespace='transactions')
    )
]

core/urls.py
from django.conf import settings
from django.urls import path
from . import views

from django.conf.urls.static import static


app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/<int:pk>/like/', views.like_post, name='like_post'),
    path('post/<int:pk>/comment/', views.comment_post, name='comment_post'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('projects/', views.projects, name='projects'),
    path('blogs/', views.blogs, name='blogs'),
    path('team/', views.team, name='team'),
    path('testimonial/', views.testimonial, name='testimonial'),
    path('faq/', views.faq, name='faq'),
    path('contact/', views.contact_view, name='contact'),
    path('error/', views.error, name='error'),
    path('adminpanel/', views.adminpanel, name='adminpanel'),
    path('admin_transactions/', views.admin_transactions, name='admin_transactions'),
    path('admin_users/', views.admin_users, name='admin_users'),
    path('contact-messages/', views.admin_contact, name='admin_contact'),
    path('contact-messages/<int:message_id>/delete/', views.delete_contact, name='delete_contact'),
    path('blog-posts/', views.admin_blog_posts, name='admin_blog_posts'),
    path('blog-posts/add/', views.add_blog_post, name='add_blog_post'),
    path('blog-posts/<int:post_id>/edit/', views.edit_blog_post, name='edit_blog_post'),
    path('blog-posts/<int:post_id>/delete/', views.delete_blog_post, name='delete_blog_post'),
    path('request/', views.fd_rd_request, name='fd_rd_request'),
    path('star-user/', views.star_user, name='star_user'),
    path('notification/', views.user_notifications, name='user_notifications'),
    path('service-request/', views.create_service_request, name='service_request'),
    path('service-request-success/', views.service_request_success, name='service_request_success'),
    path('service-requests/', views.admin_service_requests, name='admin_service_requests'),
    path('service-requests/<int:pk>/<str:status>/', views.change_request_status, name='change_request_status'),
    path('service-requests-status/', views.service_requests_status, name='service_requests_status'),
    path('service-requests/delete/<int:pk>/', views.delete_service_request, name='delete_service_request'),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transactions/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
 
from . import views

from .views import DepositMoneyView, PaymentView, TransferView, WithdrawMoneyView, TransactionRepostView, profile


app_name = 'transactions'


urlpatterns = [
    path("deposit/", DepositMoneyView.as_view(), name="deposit_money"),
    path("report/", TransactionRepostView.as_view(), name="transaction_report"),
    path("withdraw/", WithdrawMoneyView.as_view(), name="withdraw_money"),
    path('profile/', views.profile, name='profile'),
    path('transact/', views.transact, name='transact'),
    path('transfer/', TransferView.as_view(), name='transfer_form'),
    path('payment/', PaymentView.as_view(), name='payment_form'),
    path('apply-fd/', views.apply_fd, name='apply_fd'),
    path('apply-rd/', views.apply_rd, name='apply_rd'),
    path('application-success/', views.application_success, name='application_success'),
    path('fd-applications/', views.user_fd_applications, name='user_fd_applications'),
    path('rd-applications/', views.user_rd_applications, name='user_rd_applications'),
    path('fd-rd/', views.fd_rd, name='fd_rd'),
    path('approve-fd/<int:application_id>/', views.approve_fd_application, name='approve_fd_application'),
    path('reject-fd/<int:application_id>/', views.reject_fd_application, name='reject_fd_application'),
    path('approve-rd/<int:application_id>/', views.approve_rd_application, name='approve_rd_application'),
    path('reject-rd/<int:application_id>/', views.reject_rd_application, name='reject_rd_application'),
    path('status/', views.check_status, name='check_status'),
    path('fd-application/delete/<int:application_id>/', views.delete_fd_application, name='delete_fd_application'),
    path('rd-application/delete/<int:application_id>/', views.delete_rd_application, name='delete_rd_application'),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transactions/models.py
from django.db import models

from .constants import TRANSACTION_TYPE_CHOICES
from accounts.models import UserBankAccount


class Transaction(models.Model):
    account = models.ForeignKey(
        UserBankAccount,
        related_name='transactions',
        on_delete=models.CASCADE,
    )
    amount = models.DecimalField(
        decimal_places=2,
        max_digits=12
    )
    balance_after_transaction = models.DecimalField(
        decimal_places=2,
        max_digits=12
    )
    transaction_type = models.PositiveSmallIntegerField(
        choices=TRANSACTION_TYPE_CHOICES
    )
    timestamp = models.DateTimeField(auto_now_add=True)
    
    description = models.TextField(blank=True)
    ##Transfer
    
    source_account = models.CharField(max_length=100,blank=True)
    destination_account = models.CharField(max_length=100,blank=True)
    
    # Payment
    recipient_name = models.CharField(max_length=100,blank=True)
    recipient_account = models.CharField(max_length=100,blank=True)
    payment_method = models.CharField(max_length=20,blank=True, choices=[
        ('credit_card', 'Credit Card'),
        ('bank_account', 'Bank Account')
    ])
    

    def __str__(self):
        return str(self.account.account_no)

    class Meta:
        ordering = ['timestamp']


## FD and RD

# your_app/models.py

from django.db import models
from django.conf import settings  # Import settings

class FDApplication(models.Model):
    STATUS_CHOICES = [
        ('Pending', 'Pending'),
        ('Approved', 'Approved'),
        ('Rejected', 'Rejected'),
    ]

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)  # Use AUTH_USER_MODEL
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    tenure = models.PositiveIntegerField()  # in months
    interest_rate = models.DecimalField(max_digits=5, decimal_places=2)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='Pending')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"FD Application by {self.user.username} - {self.status}"

class RDApplication(models.Model):
    STATUS_CHOICES = [
        ('Pending', 'Pending'),
        ('Approved', 'Approved'),
        ('Rejected', 'Rejected'),
    ]

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)  # Use AUTH_USER_MODEL
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    tenure = models.PositiveIntegerField()  # in months
    monthly_amount = models.DecimalField(max_digits=10, decimal_places=2)
    interest_rate = models.DecimalField(max_digits=5, decimal_places=2)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='Pending')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"RD Application by {self.user.username} - {self.status}"
    




class Notification(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='notifications')
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Notification for {self.user.first_name}'

templates/transactions/application_success.html
{% extends 'core/base.html' %}
{% block head_title %}Fixed Deposit{% endblock %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="alert alert-success text-center" role="alert">
                <h4 class="alert-heading">Success!</h4>
                <p>Your application has been submitted successfully.</p>
                <hr>
                <p class="mb-0">Thank you for choosing Finovo Bank. We will process your application and get back to you soon.</p>
            </div>
        </div>
    </div>
</div>
<div><br><br><br><br><br></div>
{% endblock %}

templates/transactions/apply_fd.html
{% extends 'core/base.html' %}

{% block head_title %}Fixed Deposit{% endblock %}
{% load static %}

{% block content %}
<style>
    .background {
        background: linear-gradient(to bottom right, white, #5899E2, #5899E2, lightblue, white);
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
        backdrop-filter: blur(10px); /* Adjust blur strength as needed */
    }
    .form-container {
        background-color: rgba(255, 255, 255, 0.2); /* Adjust opacity as needed */
        max-width: 500px;
        padding: 40px;
        width: 400px;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        margin-top: 40px; /* Adjust top margin for space below header */
        margin-bottom: 40px; /* Adjust bottom margin for space above footer */
    }
    .form-title {
        font-family: 'Monospace', sans-serif;
        font-weight: bold;
        font-size: 1.875rem; /* 30px */
        text-align: center;
        margin-bottom: 20px;
    }
    .form-card {
        margin-top: 20px;
    }
    .form-label {
        display: block;
        font-weight: bold;
        margin-bottom: 8px;
        color: #273746;
    }
    .form-control {
        width: 100%; /* Adjust width as needed */
        padding: 10px;
        margin-bottom: 15px;
        border: 1px solid rgba(255, 255, 255, 0.3); /* Transparent border */
        border-radius: 5px;
        font-size: 1rem; /* 16px */
        background-color: rgba(255, 255, 255, 0.3); /* Transparent background */
        backdrop-filter: blur(5px); /* Optional: Apply blur effect to input field */
    }
    .submit-button {
        background-color: #4299e1; /* Blue color */
        color: white;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
        font-size: 1rem; /* 16px */
        transition: background-color 0.3s ease;
    }
    .submit-button:hover {
        background-color: #2b6cb0; /* Darker blue on hover */
    }
    .text-danger {
        color: #e3342f; /* Red color for errors */
    }
</style>

<div class="background">
    <div class="form-container">
        <h1 class="form-title">Apply for FD</h1>
        {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success">{{ message }}</div>
        {% endfor %}
    {% endif %}
        <form method="post" class="form-card">
            {% csrf_token %}
            
            <div class="mb-4">
                <label for="id_amount" class="form-label">Fixed Deposit Amount</label>
                <div>
                    {{ form.amount }}
                </div>
                {% if form.amount.errors %}
                    <div class="text-danger">
                        {% for error in form.amount.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            
            <div class="mb-4">
                <label for="id_tenure" class="form-label">Tenure (in months)</label>
                <div>
                    {{ form.tenure }}
                </div>
                {% if form.tenure.errors %}
                    <div class="text-danger">
                        {% for error in form.tenure.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            
            <div class="mb-4">
                <label for="id_interest_rate" class="form-label">Interest Rate</label>
                <div>
                    {{ form.interest_rate }}
                </div>
                {% if form.interest_rate.errors %}
                    <div class="text-danger">
                        {% for error in form.interest_rate.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            
            <div class="flex items-center justify-center">
                <button class="submit-button" type="submit">
                    Submit Application
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/transactions/check_status.html
{% extends 'core/base.html' %}
{% block head_title %}Service Status{% endblock %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Service Status</h1>
    <p class="lead">Welcome to the Service Status Dashboard. Here you can check the status of various services </p>

    <!-- Dropdown for service options -->
    <div class="dropdown mb-4">
        <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
            Check Services Options
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <li><a class="dropdown-item" href="{% url 'transactions:user_fd_applications' %}"><i class="fas fa-search"></i> Check FD Status</a></li>
            <li><a class="dropdown-item" href="{% url 'transactions:user_rd_applications' %}"><i class="fas fa-search"></i> Check RD Status</a></li>
            <li><a class="dropdown-item" href="{% url 'core:service_requests_status' %}"><i class="fas fa-search"></i> Check Service Status</a></li>
            <li><a class="dropdown-item" href="{% url 'core:user_notifications' %}"><i class="fas fa-star"></i> Star Customer</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'transactions:transact' %}"><i class="fas fa-exchange-alt"></i> Transact</a></li>
        </ul>
    </div>

    <!-- User Information -->
    <div class="card mb-4">
        <div class="card-header">
            <h5>User Information</h5>
        </div>
        <div class="card-body">
            <p><strong>Name:</strong> {{ user.first_name }} {{ user.last_name }}</p>
            <p><strong>Email:</strong> {{ user.email }}</p>
            
        </div>
    </div>

    <!-- Recent Transactions -->


    <!-- Quick Links -->
    <div class="card mb-4">
        <div class="card-header">
            <h5>Quick Links</h5>
        </div>
        <div class="card-body">
            <ul class="list-group">
                <li class="list-group-item"><a href="{% url 'transactions:deposit_money' %}"><i class="fas fa-money-bill-wave"></i> Deposit Money</a></li>
                <li class="list-group-item"><a href="{% url 'transactions:withdraw_money' %}"><i class="fas fa-money-bill-wave-alt"></i> Withdraw Money</a></li>
                <li class="list-group-item"><a href="{% url 'accounts:update_email' %}"><i class="fas fa-envelope"></i> Update Email</a></li>
                <li class="list-group-item"><a href="{% url 'accounts:update_password' %}"><i class="fas fa-key"></i> Update Password</a></li>
            </ul>
        </div>
    </div>

    <div id="content-area">
        <!-- Content from the selected option will be loaded here -->
    </div>
</div>
{% endblock %}

templates/transactions/payment_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block head_title %}Payment{% endblock %}
{% block content %}
<style>
    .background {
        background: linear-gradient(to bottom right,#FFFFFF, #5899E2, #5899E2 , lightblue);
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
        backdrop-filter: blur(10px); /* Adjust blur strength as needed */
    }
    .contain {
        display: flex;
        justify-content: space-between;
        align-items: flex-start; /* Align items to the top */
        width: 60%; /* Adjust as needed */
        max-width: 800px; /* Adjust max-width as needed */
        padding: 40px;
    }
    .form-contain {
        flex: 1;
        background-color: rgba(255, 255, 255, 0.2); /* Adjust opacity as needed */
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        margin-right: 20px; /* Adjust spacing between form and QR code */
    }
    .form-title {
        font-family: 'Monospace', sans-serif;
        font-weight: bold;
        font-size: 1.875rem; /* 30px */
        text-align: center;
        margin-bottom: 20px;
    }
    .form-card {
        width: 100%;
    }
    .form-label {
        display: block;
        font-weight: bold;
        margin-bottom: 8px;
        color:#273746;
    }
    .form-control {
        width: 100%;
        padding: 10px;
        margin-bottom: 15px;
        border: 1px solid rgba(255, 255, 255, 0.3);
        border-radius: 5px;
        font-size: 1rem;
        background-color: rgba(255, 255, 255, 0.3);
        backdrop-filter: blur(5px);
    }
    .submit-button {
        background-color: #4299e1;
        color: white;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
        font-size: 1rem;
        transition: background-color 0.3s ease;
    }
    .submit-button:hover {
        background-color: #2b6cb0;
    }
    .image-contain {
        width: 200px; /* Adjust width of the image contain */
        position: relative;
        margin-top: 20px;
    }
    .toggle-image {
        max-width: 100%;
        display: none; /* Initially hide the image */
    }
    .btn-toggle-image {
        background-color: #6cb2eb; /* Adjust button color */
        color: white;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
        font-size: 1rem;
        transition: background-color 0.3s ease;
    }
    .btn-toggle-image:hover {
        background-color: #5899e2; /* Darker shade on hover */
    }
</style>

<div class="background">
    <div class="contain">
        <div class="form-contain">
            <h1 class="form-title">Payment</h1>
            <form method="post" class="form-card">
                {% csrf_token %}
                
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-success">{{ message }}</div>
                    {% endfor %}
                {% endif %}
                
                <div class="mb-4">
                    {% comment %} <h5>Recipient Information</h5> {% endcomment %}
                    <label for="id_recipient_name" class="form-label">Recipient Name:</label>
                    {{ form.recipient_name }}
                    {% if form.recipient_name.errors %}
                        <div class="error-message">
                            {% for error in form.recipient_name.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-4">
                    <label for="id_recipient_account" class="form-label">Recipient Account Number:</label>
                    {{ form.recipient_account }}
                    {% if form.recipient_account.errors %}
                        <div class="error-message">
                            {% for error in form.recipient_account.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-4">
                    {% comment %} <h5>Payment Details</h5> {% endcomment %}
                    <label for="id_amount" class="form-label">Payment Amount:</label>
                    {{ form.amount }}
                    {% if form.amount.errors %}
                        <div class="error-message">
                            {% for error in form.amount.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-4">
                    <label for="id_payment_method" class="form-label">Payment Method:</label>
                    {{ form.payment_method }}
                    {% if form.payment_method.errors %}
                        <div class="error-message">
                            {% for error in form.payment_method.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <div class="mb-4">
                    <label for="id_description" class="form-label">Description:</label>
                    {{ form.description }}
                    {% if form.description.errors %}
                        <div class="error-message">
                            {% for error in form.description.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <div class="flex items-center justify-center">
                    <button type="submit" class="submit-button">Submit Payment</button>
                </div>
            </form>
        </div>

        <div class="image-contain">
            <button class="btn btn-secondary btn-toggle-image" id="toggleImageBtn">Click to Pay Using QR</button>
            <img src="{% static 'img/payment_qr.png' %}" alt="Generate QR" class="toggle-image img-fluid" id="toggleImage">
        </div>
    </div>
</div>

<script>
    document.getElementById('toggleImageBtn').addEventListener('click', function() {
        var img = document.getElementById('toggleImage');
        if (img.style.display === 'none' || img.style.display === '') {
            img.style.display = 'block';
            this.textContent = 'Remove QR';
        } else {
            img.style.display = 'none';
            this.textContent = 'Click to Pay Using QR';
        }
    });
</script>
{% endblock %}

templates/transactions/transact.html
{% extends 'core/base.html' %}

{% block head_title %}Transact{% endblock %}

{% load static%}

{% block content %}
<br>
<h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10">Transact</h1>
<div class="container mt-4">
    <div class="row">
        <div class="col-md-3">
            <div class="card text-center" style="transition: transform 0.3s;">
                <div class="card-body">
                    <img src="{% static 'img/payment.png' %}" class="card-img-top" alt="Payment">
                    <h5 class="card-title mt-3">Payment</h5>
                    <p class="card-text">Make a payment to your account or another recipient.</p>
                    <a href="{% url 'transactions:payment_form' %}" class="btn btn-primary">Go to Payment</a>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card text-center" style="transition: transform 0.3s;">
                <div class="card-body">
                    <img src="{% static 'img/transference.png' %}" class="card-img-top" alt="Transfer">
                    <h5 class="card-title mt-3">Transfer</h5>
                    <p class="card-text">Transfer money from one account to other.</p>
                    <a href="{% url 'transactions:transfer_form' %}" class="btn btn-primary">Go to Transfer</a>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card text-center" style="transition: transform 0.3s;">
                <div class="card-body">
                    <img src="{% static 'img/deposit.png' %}" class="card-img-top" alt="Deposit">
                    <h5 class="card-title mt-3">Deposit</h5>
                    <p class="card-text">Deposit funds into your account quickly and easily.</p>
                    <a href="{% url 'transactions:deposit_money' %}" class="btn btn-primary">Go to Deposit</a>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card text-center" style="transition: transform 0.3s;">
                <div class="card-body">
                    <img src="{% static 'img/withdraw.png' %}" class="card-img-top" alt="Withdraw">
                    <h5 class="card-title mt-3">Withdraw</h5>
                    <p class="card-text">Withdraw funds from your account safely and securely.</p>
                    <a href="{% url 'transactions:withdraw_money' %}" class="btn btn-primary">Go to Withdraw</a>
                </div>
            </div>
        </div>
    </div>
</div>
<br><br>
<style>
    .card:hover {
        transform: scale(1.05);
    }
</style>
{% endblock %}

templates/transactions/transfer_form.html
{% extends 'core/base.html' %}
{% block head_title %}Transfer{% endblock %}
{% load static %}
{% block content %}
<style>
    .background {
        background: linear-gradient(to bottom right,white, #5899E2, #5899E2, lightblue,white);
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
        backdrop-filter: blur(10px); /* Adjust blur strength as needed */
    }
    .form-container {
        background-color: rgba(255, 255, 255, 0.2); /* Adjust opacity as needed */
        max-width: 500px;
        padding: 40px;
        width: 400px;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        margin-top: 40px; /* Adjust top margin for space below header */
        margin-bottom: 40px; /* Adjust bottom margin for space above footer */
    }
    .form-title {
        font-family: 'Monospace', sans-serif;
        font-weight: bold;
        font-size: 1.875rem; /* 30px */
        text-align: center;
        margin-bottom: 20px;
    }
    .form-card {
        margin-top: 20px;
    }
    .form-label {
        display: block;
        font-weight: bold;
        margin-bottom: 8px;
        color: #273746;
    }
    .form-control {
        width: 100%; /* Adjust width as needed */
        padding: 10px;
        margin-bottom: 15px;
        border: 1px solid rgba(255, 255, 255, 0.3); /* Transparent border */
        border-radius: 5px;
        font-size: 1rem; /* 16px */
        background-color: rgba(255, 255, 255, 0.3); /* Transparent background */
        backdrop-filter: blur(5px); /* Optional: Apply blur effect to input field */
    }
    .submit-button {
        background-color: #4299e1; /* Blue color */
        color: white;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
        font-size: 1rem; /* 16px */
        transition: background-color 0.3s ease;
    }
    .submit-button:hover {
        background-color: #2b6cb0; /* Darker blue on hover */
    }
    .text-danger {
        color: #e3342f; /* Red color for errors */
    }
</style>

<div class="background">
    <div class="form-container">
        <h1 class="form-title">Transfer</h1>
        {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success">{{ message }}</div>
        {% endfor %}
    {% endif %}
        <form method="post" class="form-card">
            {% csrf_token %}
            
            <div class="mb-4">
                <label for="id_source_account" class="form-label">Source Account</label>
                <div>
                    {{ form.source_account }}
                </div>
                {% if form.source_account.errors %}
                    <div class="text-danger">
                        {% for error in form.source_account.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            
            <div class="mb-4">
                <label for="id_destination_account" class="form-label">Destination Account</label>
                <div>
                    {{ form.destination_account }}
                </div>
                {% if form.destination_account.errors %}
                    <div class="text-danger">
                        {% for error in form.destination_account.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            
            <div class="mb-4">
                <label for="id_amount" class="form-label">Transfer Money</label>
                <div>
                    {{ form.amount }}
                </div>
                {% if form.amount.errors %}
                    <div class="text-danger">
                        {% for error in form.amount.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            
            <div class="mb-4">
                <label for="id_description" class="form-label">Description</label>
                <div>
                    {{ form.description }}
                </div>
                {% if form.description.errors %}
                    <div class="text-danger">
                        {% for error in form.description.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            
            <div class="flex items-center justify-center">
                <button class="submit-button" type="submit">
                    Submit Transfer
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}